### ISSUE TITLE
Typo in the libvirt/server/network.sls

### ISSUE THREAD

**Issue by dis-xcom** [salt-formulas/salt-formula-libvirt#2]
https://github.com/tcpcloud/salt-formula-libvirt/blob/master/libvirt/server/network.sls#L18 

Expected:
 - contents_pillar: libvirt:server:network:{{ name }}:xml

Actual:
 - contents_pillar: libvirt:networks:{{ name }}:xml

Result:
----------
          ID: /etc/libvirt/qemu/networks/control.xml
    Function: file.managed
      Result: False
     Comment: Pillar libvirt:networks:control:xml does not exist
     Started: 12:22:15.625326
    Duration: 0.664 ms
     Changes:

**Comment by cznewt** [comment]
Hello, you are free to fix :) it seems some of the old naming did not get updated correctly

**Comment by dis-xcom** [comment]
Fixed
